spring:
  datasource:
    url: jdbc:h2:mem:dbtest;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=+1;
    name: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

  rabbitmq:
    password: '12345'
    port: '5672'
    host: localhost
    username: someNewUser