server:
  port: 8080

spring:
  profiles:
    active: local

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:dcbapp
    password: password
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: local

---

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/oliveiraapp
    password: root
  jpa:
    show-sql: 'false'
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev