spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/
  flyway:
    schemas: dbtest
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  use-management-port: false

server:
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi, swaggerui
